apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    # URL interna dentro de la red compose "posnet".
    url: http://prometheus:9090
    isDefault: true
    editable: true
