// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: notification.proto

package notificationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationChannel int32

const (
	NotificationChannel_NOTIFICATION_CHANNEL_UNSPECIFIED        NotificationChannel = 0
	NotificationChannel_NOTIFICATION_CHANNEL_TERMINAL_WEBSOCKET NotificationChannel = 1
	NotificationChannel_NOTIFICATION_CHANNEL_WEBHOOK            NotificationChannel = 2
	NotificationChannel_NOTIFICATION_CHANNEL_EMAIL              NotificationChannel = 3
	NotificationChannel_NOTIFICATION_CHANNEL_SMS                NotificationChannel = 4
)

// Enum value maps for NotificationChannel.
var (
	NotificationChannel_name = map[int32]string{
		0: "NOTIFICATION_CHANNEL_UNSPECIFIED",
		1: "NOTIFICATION_CHANNEL_TERMINAL_WEBSOCKET",
		2: "NOTIFICATION_CHANNEL_WEBHOOK",
		3: "NOTIFICATION_CHANNEL_EMAIL",
		4: "NOTIFICATION_CHANNEL_SMS",
	}
	NotificationChannel_value = map[string]int32{
		"NOTIFICATION_CHANNEL_UNSPECIFIED":        0,
		"NOTIFICATION_CHANNEL_TERMINAL_WEBSOCKET": 1,
		"NOTIFICATION_CHANNEL_WEBHOOK":            2,
		"NOTIFICATION_CHANNEL_EMAIL":              3,
		"NOTIFICATION_CHANNEL_SMS":                4,
	}
)

func (x NotificationChannel) Enum() *NotificationChannel {
	p := new(NotificationChannel)
	*p = x
	return p
}

func (x NotificationChannel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationChannel) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[0].Descriptor()
}

func (NotificationChannel) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[0]
}

func (x NotificationChannel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationChannel.Descriptor instead.
func (NotificationChannel) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

type NotificationState int32

const (
	NotificationState_NOTIFICATION_STATE_UNSPECIFIED NotificationState = 0
	NotificationState_NOTIFICATION_STATE_PENDING     NotificationState = 1
	NotificationState_NOTIFICATION_STATE_SENT        NotificationState = 2
	NotificationState_NOTIFICATION_STATE_FAILED      NotificationState = 3
	NotificationState_NOTIFICATION_STATE_RETRYING    NotificationState = 4
	NotificationState_NOTIFICATION_STATE_DEAD        NotificationState = 5
)

// Enum value maps for NotificationState.
var (
	NotificationState_name = map[int32]string{
		0: "NOTIFICATION_STATE_UNSPECIFIED",
		1: "NOTIFICATION_STATE_PENDING",
		2: "NOTIFICATION_STATE_SENT",
		3: "NOTIFICATION_STATE_FAILED",
		4: "NOTIFICATION_STATE_RETRYING",
		5: "NOTIFICATION_STATE_DEAD",
	}
	NotificationState_value = map[string]int32{
		"NOTIFICATION_STATE_UNSPECIFIED": 0,
		"NOTIFICATION_STATE_PENDING":     1,
		"NOTIFICATION_STATE_SENT":        2,
		"NOTIFICATION_STATE_FAILED":      3,
		"NOTIFICATION_STATE_RETRYING":    4,
		"NOTIFICATION_STATE_DEAD":        5,
	}
)

func (x NotificationState) Enum() *NotificationState {
	p := new(NotificationState)
	*p = x
	return p
}

func (x NotificationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationState) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[1].Descriptor()
}

func (NotificationState) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[1]
}

func (x NotificationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationState.Descriptor instead.
func (NotificationState) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

type GetNotificationStatusRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	TransactionId  string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetNotificationStatusRequest) Reset() {
	*x = GetNotificationStatusRequest{}
	mi := &file_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationStatusRequest) ProtoMessage() {}

func (x *GetNotificationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationStatusRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

func (x *GetNotificationStatusRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *GetNotificationStatusRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type GetNotificationStatusResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	TransactionId  string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	MerchantId     string                 `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Channel        NotificationChannel    `protobuf:"varint,4,opt,name=channel,proto3,enum=posnet.notification.v1.NotificationChannel" json:"channel,omitempty"`
	State          NotificationState      `protobuf:"varint,5,opt,name=state,proto3,enum=posnet.notification.v1.NotificationState" json:"state,omitempty"`
	Attempts       int32                  `protobuf:"varint,6,opt,name=attempts,proto3" json:"attempts,omitempty"`
	MaxAttempts    int32                  `protobuf:"varint,7,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	History        []*DeliveryAttempt     `protobuf:"bytes,8,rep,name=history,proto3" json:"history,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`           // RFC3339
	DispatchedAt   string                 `protobuf:"bytes,10,opt,name=dispatched_at,json=dispatchedAt,proto3" json:"dispatched_at,omitempty"` // RFC3339
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetNotificationStatusResponse) Reset() {
	*x = GetNotificationStatusResponse{}
	mi := &file_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationStatusResponse) ProtoMessage() {}

func (x *GetNotificationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationStatusResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

func (x *GetNotificationStatusResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *GetNotificationStatusResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *GetNotificationStatusResponse) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetNotificationStatusResponse) GetChannel() NotificationChannel {
	if x != nil {
		return x.Channel
	}
	return NotificationChannel_NOTIFICATION_CHANNEL_UNSPECIFIED
}

func (x *GetNotificationStatusResponse) GetState() NotificationState {
	if x != nil {
		return x.State
	}
	return NotificationState_NOTIFICATION_STATE_UNSPECIFIED
}

func (x *GetNotificationStatusResponse) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *GetNotificationStatusResponse) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *GetNotificationStatusResponse) GetHistory() []*DeliveryAttempt {
	if x != nil {
		return x.History
	}
	return nil
}

func (x *GetNotificationStatusResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *GetNotificationStatusResponse) GetDispatchedAt() string {
	if x != nil {
		return x.DispatchedAt
	}
	return ""
}

type DeliveryAttempt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AttemptNumber int32                  `protobuf:"varint,1,opt,name=attempt_number,json=attemptNumber,proto3" json:"attempt_number,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	HttpStatus    int32                  `protobuf:"varint,3,opt,name=http_status,json=httpStatus,proto3" json:"http_status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	AttemptedAt   string                 `protobuf:"bytes,5,opt,name=attempted_at,json=attemptedAt,proto3" json:"attempted_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryAttempt) Reset() {
	*x = DeliveryAttempt{}
	mi := &file_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryAttempt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryAttempt) ProtoMessage() {}

func (x *DeliveryAttempt) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryAttempt.ProtoReflect.Descriptor instead.
func (*DeliveryAttempt) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{2}
}

func (x *DeliveryAttempt) GetAttemptNumber() int32 {
	if x != nil {
		return x.AttemptNumber
	}
	return 0
}

func (x *DeliveryAttempt) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeliveryAttempt) GetHttpStatus() int32 {
	if x != nil {
		return x.HttpStatus
	}
	return 0
}

func (x *DeliveryAttempt) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DeliveryAttempt) GetAttemptedAt() string {
	if x != nil {
		return x.AttemptedAt
	}
	return ""
}

type RetryNotificationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	OperatorId     string                 `protobuf:"bytes,2,opt,name=operator_id,json=operatorId,proto3" json:"operator_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RetryNotificationRequest) Reset() {
	*x = RetryNotificationRequest{}
	mi := &file_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryNotificationRequest) ProtoMessage() {}

func (x *RetryNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryNotificationRequest.ProtoReflect.Descriptor instead.
func (*RetryNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{3}
}

func (x *RetryNotificationRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *RetryNotificationRequest) GetOperatorId() string {
	if x != nil {
		return x.OperatorId
	}
	return ""
}

type RetryNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorReason   string                 `protobuf:"bytes,2,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryNotificationResponse) Reset() {
	*x = RetryNotificationResponse{}
	mi := &file_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryNotificationResponse) ProtoMessage() {}

func (x *RetryNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryNotificationResponse.ProtoReflect.Descriptor instead.
func (*RetryNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{4}
}

func (x *RetryNotificationResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RetryNotificationResponse) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

type ListFailedWebhooksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MerchantId    string                 `protobuf:"bytes,1,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFailedWebhooksRequest) Reset() {
	*x = ListFailedWebhooksRequest{}
	mi := &file_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFailedWebhooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFailedWebhooksRequest) ProtoMessage() {}

func (x *ListFailedWebhooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFailedWebhooksRequest.ProtoReflect.Descriptor instead.
func (*ListFailedWebhooksRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{5}
}

func (x *ListFailedWebhooksRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *ListFailedWebhooksRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListFailedWebhooksRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListFailedWebhooksResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Webhooks      []*FailedWebhookSummary `protobuf:"bytes,1,rep,name=webhooks,proto3" json:"webhooks,omitempty"`
	NextPageToken string                  `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFailedWebhooksResponse) Reset() {
	*x = ListFailedWebhooksResponse{}
	mi := &file_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFailedWebhooksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFailedWebhooksResponse) ProtoMessage() {}

func (x *ListFailedWebhooksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFailedWebhooksResponse.ProtoReflect.Descriptor instead.
func (*ListFailedWebhooksResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{6}
}

func (x *ListFailedWebhooksResponse) GetWebhooks() []*FailedWebhookSummary {
	if x != nil {
		return x.Webhooks
	}
	return nil
}

func (x *ListFailedWebhooksResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type FailedWebhookSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	TransactionId  string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	MerchantId     string                 `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	State          NotificationState      `protobuf:"varint,4,opt,name=state,proto3,enum=posnet.notification.v1.NotificationState" json:"state,omitempty"`
	Attempts       int32                  `protobuf:"varint,5,opt,name=attempts,proto3" json:"attempts,omitempty"`
	LastAttemptAt  string                 `protobuf:"bytes,6,opt,name=last_attempt_at,json=lastAttemptAt,proto3" json:"last_attempt_at,omitempty"` // RFC3339
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FailedWebhookSummary) Reset() {
	*x = FailedWebhookSummary{}
	mi := &file_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailedWebhookSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailedWebhookSummary) ProtoMessage() {}

func (x *FailedWebhookSummary) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailedWebhookSummary.ProtoReflect.Descriptor instead.
func (*FailedWebhookSummary) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{7}
}

func (x *FailedWebhookSummary) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *FailedWebhookSummary) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *FailedWebhookSummary) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *FailedWebhookSummary) GetState() NotificationState {
	if x != nil {
		return x.State
	}
	return NotificationState_NOTIFICATION_STATE_UNSPECIFIED
}

func (x *FailedWebhookSummary) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *FailedWebhookSummary) GetLastAttemptAt() string {
	if x != nil {
		return x.LastAttemptAt
	}
	return ""
}

var File_notification_proto protoreflect.FileDescriptor

const file_notification_proto_rawDesc = "" +
	"\n" +
	"\x12notification.proto\x12\x16posnet.notification.v1\"n\n" +
	"\x1cGetNotificationStatusRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\"\xde\x03\n" +
	"\x1dGetNotificationStatusResponse\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\tR\n" +
	"merchantId\x12E\n" +
	"\achannel\x18\x04 \x01(\x0e2+.posnet.notification.v1.NotificationChannelR\achannel\x12?\n" +
	"\x05state\x18\x05 \x01(\x0e2).posnet.notification.v1.NotificationStateR\x05state\x12\x1a\n" +
	"\battempts\x18\x06 \x01(\x05R\battempts\x12!\n" +
	"\fmax_attempts\x18\a \x01(\x05R\vmaxAttempts\x12A\n" +
	"\ahistory\x18\b \x03(\v2'.posnet.notification.v1.DeliveryAttemptR\ahistory\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12#\n" +
	"\rdispatched_at\x18\n" +
	" \x01(\tR\fdispatchedAt\"\xbb\x01\n" +
	"\x0fDeliveryAttempt\x12%\n" +
	"\x0eattempt_number\x18\x01 \x01(\x05R\rattemptNumber\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x1f\n" +
	"\vhttp_status\x18\x03 \x01(\x05R\n" +
	"httpStatus\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage\x12!\n" +
	"\fattempted_at\x18\x05 \x01(\tR\vattemptedAt\"d\n" +
	"\x18RetryNotificationRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x1f\n" +
	"\voperator_id\x18\x02 \x01(\tR\n" +
	"operatorId\"Z\n" +
	"\x19RetryNotificationResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12!\n" +
	"\ferror_reason\x18\x02 \x01(\tR\verrorReason\"x\n" +
	"\x19ListFailedWebhooksRequest\x12\x1f\n" +
	"\vmerchant_id\x18\x01 \x01(\tR\n" +
	"merchantId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x8e\x01\n" +
	"\x1aListFailedWebhooksResponse\x12H\n" +
	"\bwebhooks\x18\x01 \x03(\v2,.posnet.notification.v1.FailedWebhookSummaryR\bwebhooks\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x8c\x02\n" +
	"\x14FailedWebhookSummary\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\tR\n" +
	"merchantId\x12?\n" +
	"\x05state\x18\x04 \x01(\x0e2).posnet.notification.v1.NotificationStateR\x05state\x12\x1a\n" +
	"\battempts\x18\x05 \x01(\x05R\battempts\x12&\n" +
	"\x0flast_attempt_at\x18\x06 \x01(\tR\rlastAttemptAt*\xc8\x01\n" +
	"\x13NotificationChannel\x12$\n" +
	" NOTIFICATION_CHANNEL_UNSPECIFIED\x10\x00\x12+\n" +
	"'NOTIFICATION_CHANNEL_TERMINAL_WEBSOCKET\x10\x01\x12 \n" +
	"\x1cNOTIFICATION_CHANNEL_WEBHOOK\x10\x02\x12\x1e\n" +
	"\x1aNOTIFICATION_CHANNEL_EMAIL\x10\x03\x12\x1c\n" +
	"\x18NOTIFICATION_CHANNEL_SMS\x10\x04*\xd1\x01\n" +
	"\x11NotificationState\x12\"\n" +
	"\x1eNOTIFICATION_STATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aNOTIFICATION_STATE_PENDING\x10\x01\x12\x1b\n" +
	"\x17NOTIFICATION_STATE_SENT\x10\x02\x12\x1d\n" +
	"\x19NOTIFICATION_STATE_FAILED\x10\x03\x12\x1f\n" +
	"\x1bNOTIFICATION_STATE_RETRYING\x10\x04\x12\x1b\n" +
	"\x17NOTIFICATION_STATE_DEAD\x10\x052\x93\x03\n" +
	"\x13NotificationService\x12\x84\x01\n" +
	"\x15GetNotificationStatus\x124.posnet.notification.v1.GetNotificationStatusRequest\x1a5.posnet.notification.v1.GetNotificationStatusResponse\x12x\n" +
	"\x11RetryNotification\x120.posnet.notification.v1.RetryNotificationRequest\x1a1.posnet.notification.v1.RetryNotificationResponse\x12{\n" +
	"\x12ListFailedWebhooks\x121.posnet.notification.v1.ListFailedWebhooksRequest\x1a2.posnet.notification.v1.ListFailedWebhooksResponseBIZGgithub.com/juantevez/go-posnet/pkg/proto/notification/v1;notificationv1b\x06proto3"

var (
	file_notification_proto_rawDescOnce sync.Once
	file_notification_proto_rawDescData []byte
)

func file_notification_proto_rawDescGZIP() []byte {
	file_notification_proto_rawDescOnce.Do(func() {
		file_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)))
	})
	return file_notification_proto_rawDescData
}

var file_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_notification_proto_goTypes = []any{
	(NotificationChannel)(0),              // 0: posnet.notification.v1.NotificationChannel
	(NotificationState)(0),                // 1: posnet.notification.v1.NotificationState
	(*GetNotificationStatusRequest)(nil),  // 2: posnet.notification.v1.GetNotificationStatusRequest
	(*GetNotificationStatusResponse)(nil), // 3: posnet.notification.v1.GetNotificationStatusResponse
	(*DeliveryAttempt)(nil),               // 4: posnet.notification.v1.DeliveryAttempt
	(*RetryNotificationRequest)(nil),      // 5: posnet.notification.v1.RetryNotificationRequest
	(*RetryNotificationResponse)(nil),     // 6: posnet.notification.v1.RetryNotificationResponse
	(*ListFailedWebhooksRequest)(nil),     // 7: posnet.notification.v1.ListFailedWebhooksRequest
	(*ListFailedWebhooksResponse)(nil),    // 8: posnet.notification.v1.ListFailedWebhooksResponse
	(*FailedWebhookSummary)(nil),          // 9: posnet.notification.v1.FailedWebhookSummary
}
var file_notification_proto_depIdxs = []int32{
	0, // 0: posnet.notification.v1.GetNotificationStatusResponse.channel:type_name -> posnet.notification.v1.NotificationChannel
	1, // 1: posnet.notification.v1.GetNotificationStatusResponse.state:type_name -> posnet.notification.v1.NotificationState
	4, // 2: posnet.notification.v1.GetNotificationStatusResponse.history:type_name -> posnet.notification.v1.DeliveryAttempt
	9, // 3: posnet.notification.v1.ListFailedWebhooksResponse.webhooks:type_name -> posnet.notification.v1.FailedWebhookSummary
	1, // 4: posnet.notification.v1.FailedWebhookSummary.state:type_name -> posnet.notification.v1.NotificationState
	2, // 5: posnet.notification.v1.NotificationService.GetNotificationStatus:input_type -> posnet.notification.v1.GetNotificationStatusRequest
	5, // 6: posnet.notification.v1.NotificationService.RetryNotification:input_type -> posnet.notification.v1.RetryNotificationRequest
	7, // 7: posnet.notification.v1.NotificationService.ListFailedWebhooks:input_type -> posnet.notification.v1.ListFailedWebhooksRequest
	3, // 8: posnet.notification.v1.NotificationService.GetNotificationStatus:output_type -> posnet.notification.v1.GetNotificationStatusResponse
	6, // 9: posnet.notification.v1.NotificationService.RetryNotification:output_type -> posnet.notification.v1.RetryNotificationResponse
	8, // 10: posnet.notification.v1.NotificationService.ListFailedWebhooks:output_type -> posnet.notification.v1.ListFailedWebhooksResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_notification_proto_init() }
func file_notification_proto_init() {
	if File_notification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_proto_goTypes,
		DependencyIndexes: file_notification_proto_depIdxs,
		EnumInfos:         file_notification_proto_enumTypes,
		MessageInfos:      file_notification_proto_msgTypes,
	}.Build()
	File_notification_proto = out.File
	file_notification_proto_goTypes = nil
	file_notification_proto_depIdxs = nil
}
