// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: authorization.proto

package authorizationv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionState int32

const (
	TransactionState_TRANSACTION_STATE_UNSPECIFIED    TransactionState = 0
	TransactionState_TRANSACTION_STATE_RECEIVED       TransactionState = 1
	TransactionState_TRANSACTION_STATE_FRAUD_CHECKING TransactionState = 2
	TransactionState_TRANSACTION_STATE_PROCESSING     TransactionState = 3
	TransactionState_TRANSACTION_STATE_APPROVED       TransactionState = 4
	TransactionState_TRANSACTION_STATE_REJECTED       TransactionState = 5
	TransactionState_TRANSACTION_STATE_INDETERMINATE  TransactionState = 6
	TransactionState_TRANSACTION_STATE_REVERSED       TransactionState = 7
)

// Enum value maps for TransactionState.
var (
	TransactionState_name = map[int32]string{
		0: "TRANSACTION_STATE_UNSPECIFIED",
		1: "TRANSACTION_STATE_RECEIVED",
		2: "TRANSACTION_STATE_FRAUD_CHECKING",
		3: "TRANSACTION_STATE_PROCESSING",
		4: "TRANSACTION_STATE_APPROVED",
		5: "TRANSACTION_STATE_REJECTED",
		6: "TRANSACTION_STATE_INDETERMINATE",
		7: "TRANSACTION_STATE_REVERSED",
	}
	TransactionState_value = map[string]int32{
		"TRANSACTION_STATE_UNSPECIFIED":    0,
		"TRANSACTION_STATE_RECEIVED":       1,
		"TRANSACTION_STATE_FRAUD_CHECKING": 2,
		"TRANSACTION_STATE_PROCESSING":     3,
		"TRANSACTION_STATE_APPROVED":       4,
		"TRANSACTION_STATE_REJECTED":       5,
		"TRANSACTION_STATE_INDETERMINATE":  6,
		"TRANSACTION_STATE_REVERSED":       7,
	}
)

func (x TransactionState) Enum() *TransactionState {
	p := new(TransactionState)
	*p = x
	return p
}

func (x TransactionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionState) Descriptor() protoreflect.EnumDescriptor {
	return file_authorization_proto_enumTypes[0].Descriptor()
}

func (TransactionState) Type() protoreflect.EnumType {
	return &file_authorization_proto_enumTypes[0]
}

func (x TransactionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionState.Descriptor instead.
func (TransactionState) EnumDescriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{0}
}

type GetTransactionStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionStatusRequest) Reset() {
	*x = GetTransactionStatusRequest{}
	mi := &file_authorization_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionStatusRequest) ProtoMessage() {}

func (x *GetTransactionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionStatusRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{0}
}

func (x *GetTransactionStatusRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type GetTransactionStatusResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	TerminalId      string                 `protobuf:"bytes,2,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	MerchantId      string                 `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	State           TransactionState       `protobuf:"varint,4,opt,name=state,proto3,enum=posnet.authorization.v1.TransactionState" json:"state,omitempty"`
	AmountCents     int64                  `protobuf:"varint,5,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Currency        string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	CardLast4       string                 `protobuf:"bytes,7,opt,name=card_last4,json=cardLast4,proto3" json:"card_last4,omitempty"`
	CardNetwork     string                 `protobuf:"bytes,8,opt,name=card_network,json=cardNetwork,proto3" json:"card_network,omitempty"`
	EntryMode       string                 `protobuf:"bytes,9,opt,name=entry_mode,json=entryMode,proto3" json:"entry_mode,omitempty"`
	AuthCode        string                 `protobuf:"bytes,10,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"`
	RejectionCode   string                 `protobuf:"bytes,11,opt,name=rejection_code,json=rejectionCode,proto3" json:"rejection_code,omitempty"`
	RejectionReason string                 `protobuf:"bytes,12,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	RejectionSource string                 `protobuf:"bytes,13,opt,name=rejection_source,json=rejectionSource,proto3" json:"rejection_source,omitempty"`
	FraudScore      int32                  `protobuf:"varint,14,opt,name=fraud_score,json=fraudScore,proto3" json:"fraud_score,omitempty"`
	FraudDecision   string                 `protobuf:"bytes,15,opt,name=fraud_decision,json=fraudDecision,proto3" json:"fraud_decision,omitempty"`
	// Timestamps como RFC3339 string — sin depender de google/protobuf/timestamp.proto
	ReceivedAt    string `protobuf:"bytes,16,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	AuthorizedAt  string `protobuf:"bytes,17,opt,name=authorized_at,json=authorizedAt,proto3" json:"authorized_at,omitempty"`
	RejectedAt    string `protobuf:"bytes,18,opt,name=rejected_at,json=rejectedAt,proto3" json:"rejected_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionStatusResponse) Reset() {
	*x = GetTransactionStatusResponse{}
	mi := &file_authorization_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionStatusResponse) ProtoMessage() {}

func (x *GetTransactionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionStatusResponse) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{1}
}

func (x *GetTransactionStatusResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *GetTransactionStatusResponse) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *GetTransactionStatusResponse) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetTransactionStatusResponse) GetState() TransactionState {
	if x != nil {
		return x.State
	}
	return TransactionState_TRANSACTION_STATE_UNSPECIFIED
}

func (x *GetTransactionStatusResponse) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *GetTransactionStatusResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetTransactionStatusResponse) GetCardLast4() string {
	if x != nil {
		return x.CardLast4
	}
	return ""
}

func (x *GetTransactionStatusResponse) GetCardNetwork() string {
	if x != nil {
		return x.CardNetwork
	}
	return ""
}

func (x *GetTransactionStatusResponse) GetEntryMode() string {
	if x != nil {
		return x.EntryMode
	}
	return ""
}

func (x *GetTransactionStatusResponse) GetAuthCode() string {
	if x != nil {
		return x.AuthCode
	}
	return ""
}

func (x *GetTransactionStatusResponse) GetRejectionCode() string {
	if x != nil {
		return x.RejectionCode
	}
	return ""
}

func (x *GetTransactionStatusResponse) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *GetTransactionStatusResponse) GetRejectionSource() string {
	if x != nil {
		return x.RejectionSource
	}
	return ""
}

func (x *GetTransactionStatusResponse) GetFraudScore() int32 {
	if x != nil {
		return x.FraudScore
	}
	return 0
}

func (x *GetTransactionStatusResponse) GetFraudDecision() string {
	if x != nil {
		return x.FraudDecision
	}
	return ""
}

func (x *GetTransactionStatusResponse) GetReceivedAt() string {
	if x != nil {
		return x.ReceivedAt
	}
	return ""
}

func (x *GetTransactionStatusResponse) GetAuthorizedAt() string {
	if x != nil {
		return x.AuthorizedAt
	}
	return ""
}

func (x *GetTransactionStatusResponse) GetRejectedAt() string {
	if x != nil {
		return x.RejectedAt
	}
	return ""
}

type ListTerminalTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TerminalId    string                 `protobuf:"bytes,1,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTerminalTransactionsRequest) Reset() {
	*x = ListTerminalTransactionsRequest{}
	mi := &file_authorization_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTerminalTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTerminalTransactionsRequest) ProtoMessage() {}

func (x *ListTerminalTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTerminalTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTerminalTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{2}
}

func (x *ListTerminalTransactionsRequest) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *ListTerminalTransactionsRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *ListTerminalTransactionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListTerminalTransactionsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type ListTerminalTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*TransactionSummary  `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTerminalTransactionsResponse) Reset() {
	*x = ListTerminalTransactionsResponse{}
	mi := &file_authorization_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTerminalTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTerminalTransactionsResponse) ProtoMessage() {}

func (x *ListTerminalTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTerminalTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTerminalTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{3}
}

func (x *ListTerminalTransactionsResponse) GetTransactions() []*TransactionSummary {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListTerminalTransactionsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

func (x *ListTerminalTransactionsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type TransactionSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	State         TransactionState       `protobuf:"varint,2,opt,name=state,proto3,enum=posnet.authorization.v1.TransactionState" json:"state,omitempty"`
	AmountCents   int64                  `protobuf:"varint,3,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	AuthCode      string                 `protobuf:"bytes,5,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"`
	RejectionCode string                 `protobuf:"bytes,6,opt,name=rejection_code,json=rejectionCode,proto3" json:"rejection_code,omitempty"`
	TransactionAt string                 `protobuf:"bytes,7,opt,name=transaction_at,json=transactionAt,proto3" json:"transaction_at,omitempty"` // RFC3339
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionSummary) Reset() {
	*x = TransactionSummary{}
	mi := &file_authorization_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionSummary) ProtoMessage() {}

func (x *TransactionSummary) ProtoReflect() protoreflect.Message {
	mi := &file_authorization_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionSummary.ProtoReflect.Descriptor instead.
func (*TransactionSummary) Descriptor() ([]byte, []int) {
	return file_authorization_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionSummary) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionSummary) GetState() TransactionState {
	if x != nil {
		return x.State
	}
	return TransactionState_TRANSACTION_STATE_UNSPECIFIED
}

func (x *TransactionSummary) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *TransactionSummary) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *TransactionSummary) GetAuthCode() string {
	if x != nil {
		return x.AuthCode
	}
	return ""
}

func (x *TransactionSummary) GetRejectionCode() string {
	if x != nil {
		return x.RejectionCode
	}
	return ""
}

func (x *TransactionSummary) GetTransactionAt() string {
	if x != nil {
		return x.TransactionAt
	}
	return ""
}

var File_authorization_proto protoreflect.FileDescriptor

const file_authorization_proto_rawDesc = "" +
	"\n" +
	"\x13authorization.proto\x12\x17posnet.authorization.v1\"D\n" +
	"\x1bGetTransactionStatusRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"\xb1\x05\n" +
	"\x1cGetTransactionStatusResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1f\n" +
	"\vterminal_id\x18\x02 \x01(\tR\n" +
	"terminalId\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\tR\n" +
	"merchantId\x12?\n" +
	"\x05state\x18\x04 \x01(\x0e2).posnet.authorization.v1.TransactionStateR\x05state\x12!\n" +
	"\famount_cents\x18\x05 \x01(\x03R\vamountCents\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"card_last4\x18\a \x01(\tR\tcardLast4\x12!\n" +
	"\fcard_network\x18\b \x01(\tR\vcardNetwork\x12\x1d\n" +
	"\n" +
	"entry_mode\x18\t \x01(\tR\tentryMode\x12\x1b\n" +
	"\tauth_code\x18\n" +
	" \x01(\tR\bauthCode\x12%\n" +
	"\x0erejection_code\x18\v \x01(\tR\rrejectionCode\x12)\n" +
	"\x10rejection_reason\x18\f \x01(\tR\x0frejectionReason\x12)\n" +
	"\x10rejection_source\x18\r \x01(\tR\x0frejectionSource\x12\x1f\n" +
	"\vfraud_score\x18\x0e \x01(\x05R\n" +
	"fraudScore\x12%\n" +
	"\x0efraud_decision\x18\x0f \x01(\tR\rfraudDecision\x12\x1f\n" +
	"\vreceived_at\x18\x10 \x01(\tR\n" +
	"receivedAt\x12#\n" +
	"\rauthorized_at\x18\x11 \x01(\tR\fauthorizedAt\x12\x1f\n" +
	"\vrejected_at\x18\x12 \x01(\tR\n" +
	"rejectedAt\"\x92\x01\n" +
	"\x1fListTerminalTransactionsRequest\x12\x1f\n" +
	"\vterminal_id\x18\x01 \x01(\tR\n" +
	"terminalId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tR\tpageToken\"\xbc\x01\n" +
	" ListTerminalTransactionsResponse\x12O\n" +
	"\ftransactions\x18\x01 \x03(\v2+.posnet.authorization.v1.TransactionSummaryR\ftransactions\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\x12\x1f\n" +
	"\vtotal_count\x18\x03 \x01(\x05R\n" +
	"totalCount\"\xa6\x02\n" +
	"\x12TransactionSummary\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12?\n" +
	"\x05state\x18\x02 \x01(\x0e2).posnet.authorization.v1.TransactionStateR\x05state\x12!\n" +
	"\famount_cents\x18\x03 \x01(\x03R\vamountCents\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1b\n" +
	"\tauth_code\x18\x05 \x01(\tR\bauthCode\x12%\n" +
	"\x0erejection_code\x18\x06 \x01(\tR\rrejectionCode\x12%\n" +
	"\x0etransaction_at\x18\a \x01(\tR\rtransactionAt*\xa2\x02\n" +
	"\x10TransactionState\x12!\n" +
	"\x1dTRANSACTION_STATE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTRANSACTION_STATE_RECEIVED\x10\x01\x12$\n" +
	" TRANSACTION_STATE_FRAUD_CHECKING\x10\x02\x12 \n" +
	"\x1cTRANSACTION_STATE_PROCESSING\x10\x03\x12\x1e\n" +
	"\x1aTRANSACTION_STATE_APPROVED\x10\x04\x12\x1e\n" +
	"\x1aTRANSACTION_STATE_REJECTED\x10\x05\x12#\n" +
	"\x1fTRANSACTION_STATE_INDETERMINATE\x10\x06\x12\x1e\n" +
	"\x1aTRANSACTION_STATE_REVERSED\x10\a2\xae\x02\n" +
	"\x14AuthorizationService\x12\x83\x01\n" +
	"\x14GetTransactionStatus\x124.posnet.authorization.v1.GetTransactionStatusRequest\x1a5.posnet.authorization.v1.GetTransactionStatusResponse\x12\x8f\x01\n" +
	"\x18ListTerminalTransactions\x128.posnet.authorization.v1.ListTerminalTransactionsRequest\x1a9.posnet.authorization.v1.ListTerminalTransactionsResponseBKZIgithub.com/juantevez/go-posnet/pkg/proto/authorization/v1;authorizationv1b\x06proto3"

var (
	file_authorization_proto_rawDescOnce sync.Once
	file_authorization_proto_rawDescData []byte
)

func file_authorization_proto_rawDescGZIP() []byte {
	file_authorization_proto_rawDescOnce.Do(func() {
		file_authorization_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authorization_proto_rawDesc), len(file_authorization_proto_rawDesc)))
	})
	return file_authorization_proto_rawDescData
}

var file_authorization_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_authorization_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_authorization_proto_goTypes = []any{
	(TransactionState)(0),                    // 0: posnet.authorization.v1.TransactionState
	(*GetTransactionStatusRequest)(nil),      // 1: posnet.authorization.v1.GetTransactionStatusRequest
	(*GetTransactionStatusResponse)(nil),     // 2: posnet.authorization.v1.GetTransactionStatusResponse
	(*ListTerminalTransactionsRequest)(nil),  // 3: posnet.authorization.v1.ListTerminalTransactionsRequest
	(*ListTerminalTransactionsResponse)(nil), // 4: posnet.authorization.v1.ListTerminalTransactionsResponse
	(*TransactionSummary)(nil),               // 5: posnet.authorization.v1.TransactionSummary
}
var file_authorization_proto_depIdxs = []int32{
	0, // 0: posnet.authorization.v1.GetTransactionStatusResponse.state:type_name -> posnet.authorization.v1.TransactionState
	5, // 1: posnet.authorization.v1.ListTerminalTransactionsResponse.transactions:type_name -> posnet.authorization.v1.TransactionSummary
	0, // 2: posnet.authorization.v1.TransactionSummary.state:type_name -> posnet.authorization.v1.TransactionState
	1, // 3: posnet.authorization.v1.AuthorizationService.GetTransactionStatus:input_type -> posnet.authorization.v1.GetTransactionStatusRequest
	3, // 4: posnet.authorization.v1.AuthorizationService.ListTerminalTransactions:input_type -> posnet.authorization.v1.ListTerminalTransactionsRequest
	2, // 5: posnet.authorization.v1.AuthorizationService.GetTransactionStatus:output_type -> posnet.authorization.v1.GetTransactionStatusResponse
	4, // 6: posnet.authorization.v1.AuthorizationService.ListTerminalTransactions:output_type -> posnet.authorization.v1.ListTerminalTransactionsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_authorization_proto_init() }
func file_authorization_proto_init() {
	if File_authorization_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authorization_proto_rawDesc), len(file_authorization_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authorization_proto_goTypes,
		DependencyIndexes: file_authorization_proto_depIdxs,
		EnumInfos:         file_authorization_proto_enumTypes,
		MessageInfos:      file_authorization_proto_msgTypes,
	}.Build()
	File_authorization_proto = out.File
	file_authorization_proto_goTypes = nil
	file_authorization_proto_depIdxs = nil
}
