// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: terminal_gateway.proto

package terminalgatewayv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TerminalGatewayService_SendReceipt_FullMethodName       = "/posnet.terminalgateway.v1.TerminalGatewayService/SendReceipt"
	TerminalGatewayService_GetTerminalStatus_FullMethodName = "/posnet.terminalgateway.v1.TerminalGatewayService/GetTerminalStatus"
)

// TerminalGatewayServiceClient is the client API for TerminalGatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TerminalGatewayService — llamado por Notification para entregar comprobantes.
type TerminalGatewayServiceClient interface {
	SendReceipt(ctx context.Context, in *SendReceiptRequest, opts ...grpc.CallOption) (*SendReceiptResponse, error)
	GetTerminalStatus(ctx context.Context, in *GetTerminalStatusRequest, opts ...grpc.CallOption) (*GetTerminalStatusResponse, error)
}

type terminalGatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTerminalGatewayServiceClient(cc grpc.ClientConnInterface) TerminalGatewayServiceClient {
	return &terminalGatewayServiceClient{cc}
}

func (c *terminalGatewayServiceClient) SendReceipt(ctx context.Context, in *SendReceiptRequest, opts ...grpc.CallOption) (*SendReceiptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendReceiptResponse)
	err := c.cc.Invoke(ctx, TerminalGatewayService_SendReceipt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *terminalGatewayServiceClient) GetTerminalStatus(ctx context.Context, in *GetTerminalStatusRequest, opts ...grpc.CallOption) (*GetTerminalStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTerminalStatusResponse)
	err := c.cc.Invoke(ctx, TerminalGatewayService_GetTerminalStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TerminalGatewayServiceServer is the server API for TerminalGatewayService service.
// All implementations must embed UnimplementedTerminalGatewayServiceServer
// for forward compatibility.
//
// TerminalGatewayService — llamado por Notification para entregar comprobantes.
type TerminalGatewayServiceServer interface {
	SendReceipt(context.Context, *SendReceiptRequest) (*SendReceiptResponse, error)
	GetTerminalStatus(context.Context, *GetTerminalStatusRequest) (*GetTerminalStatusResponse, error)
	mustEmbedUnimplementedTerminalGatewayServiceServer()
}

// UnimplementedTerminalGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTerminalGatewayServiceServer struct{}

func (UnimplementedTerminalGatewayServiceServer) SendReceipt(context.Context, *SendReceiptRequest) (*SendReceiptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendReceipt not implemented")
}
func (UnimplementedTerminalGatewayServiceServer) GetTerminalStatus(context.Context, *GetTerminalStatusRequest) (*GetTerminalStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTerminalStatus not implemented")
}
func (UnimplementedTerminalGatewayServiceServer) mustEmbedUnimplementedTerminalGatewayServiceServer() {
}
func (UnimplementedTerminalGatewayServiceServer) testEmbeddedByValue() {}

// UnsafeTerminalGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TerminalGatewayServiceServer will
// result in compilation errors.
type UnsafeTerminalGatewayServiceServer interface {
	mustEmbedUnimplementedTerminalGatewayServiceServer()
}

func RegisterTerminalGatewayServiceServer(s grpc.ServiceRegistrar, srv TerminalGatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedTerminalGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TerminalGatewayService_ServiceDesc, srv)
}

func _TerminalGatewayService_SendReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendReceiptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalGatewayServiceServer).SendReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalGatewayService_SendReceipt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalGatewayServiceServer).SendReceipt(ctx, req.(*SendReceiptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TerminalGatewayService_GetTerminalStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTerminalStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TerminalGatewayServiceServer).GetTerminalStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TerminalGatewayService_GetTerminalStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TerminalGatewayServiceServer).GetTerminalStatus(ctx, req.(*GetTerminalStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TerminalGatewayService_ServiceDesc is the grpc.ServiceDesc for TerminalGatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TerminalGatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "posnet.terminalgateway.v1.TerminalGatewayService",
	HandlerType: (*TerminalGatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendReceipt",
			Handler:    _TerminalGatewayService_SendReceipt_Handler,
		},
		{
			MethodName: "GetTerminalStatus",
			Handler:    _TerminalGatewayService_GetTerminalStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "terminal_gateway.proto",
}
