// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: terminal_gateway.proto

package terminalgatewayv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReceiptResult int32

const (
	ReceiptResult_RECEIPT_RESULT_UNSPECIFIED ReceiptResult = 0
	ReceiptResult_RECEIPT_RESULT_APPROVED    ReceiptResult = 1
	ReceiptResult_RECEIPT_RESULT_REJECTED    ReceiptResult = 2
	ReceiptResult_RECEIPT_RESULT_REVERSED    ReceiptResult = 3
)

// Enum value maps for ReceiptResult.
var (
	ReceiptResult_name = map[int32]string{
		0: "RECEIPT_RESULT_UNSPECIFIED",
		1: "RECEIPT_RESULT_APPROVED",
		2: "RECEIPT_RESULT_REJECTED",
		3: "RECEIPT_RESULT_REVERSED",
	}
	ReceiptResult_value = map[string]int32{
		"RECEIPT_RESULT_UNSPECIFIED": 0,
		"RECEIPT_RESULT_APPROVED":    1,
		"RECEIPT_RESULT_REJECTED":    2,
		"RECEIPT_RESULT_REVERSED":    3,
	}
)

func (x ReceiptResult) Enum() *ReceiptResult {
	p := new(ReceiptResult)
	*p = x
	return p
}

func (x ReceiptResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReceiptResult) Descriptor() protoreflect.EnumDescriptor {
	return file_terminal_gateway_proto_enumTypes[0].Descriptor()
}

func (ReceiptResult) Type() protoreflect.EnumType {
	return &file_terminal_gateway_proto_enumTypes[0]
}

func (x ReceiptResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReceiptResult.Descriptor instead.
func (ReceiptResult) EnumDescriptor() ([]byte, []int) {
	return file_terminal_gateway_proto_rawDescGZIP(), []int{0}
}

type TerminalConnectionStatus int32

const (
	TerminalConnectionStatus_TERMINAL_CONNECTION_STATUS_UNSPECIFIED  TerminalConnectionStatus = 0
	TerminalConnectionStatus_TERMINAL_CONNECTION_STATUS_CONNECTED    TerminalConnectionStatus = 1
	TerminalConnectionStatus_TERMINAL_CONNECTION_STATUS_DISCONNECTED TerminalConnectionStatus = 2
	TerminalConnectionStatus_TERMINAL_CONNECTION_STATUS_UNKNOWN      TerminalConnectionStatus = 3
)

// Enum value maps for TerminalConnectionStatus.
var (
	TerminalConnectionStatus_name = map[int32]string{
		0: "TERMINAL_CONNECTION_STATUS_UNSPECIFIED",
		1: "TERMINAL_CONNECTION_STATUS_CONNECTED",
		2: "TERMINAL_CONNECTION_STATUS_DISCONNECTED",
		3: "TERMINAL_CONNECTION_STATUS_UNKNOWN",
	}
	TerminalConnectionStatus_value = map[string]int32{
		"TERMINAL_CONNECTION_STATUS_UNSPECIFIED":  0,
		"TERMINAL_CONNECTION_STATUS_CONNECTED":    1,
		"TERMINAL_CONNECTION_STATUS_DISCONNECTED": 2,
		"TERMINAL_CONNECTION_STATUS_UNKNOWN":      3,
	}
)

func (x TerminalConnectionStatus) Enum() *TerminalConnectionStatus {
	p := new(TerminalConnectionStatus)
	*p = x
	return p
}

func (x TerminalConnectionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TerminalConnectionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_terminal_gateway_proto_enumTypes[1].Descriptor()
}

func (TerminalConnectionStatus) Type() protoreflect.EnumType {
	return &file_terminal_gateway_proto_enumTypes[1]
}

func (x TerminalConnectionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TerminalConnectionStatus.Descriptor instead.
func (TerminalConnectionStatus) EnumDescriptor() ([]byte, []int) {
	return file_terminal_gateway_proto_rawDescGZIP(), []int{1}
}

type SendReceiptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TerminalId    string                 `protobuf:"bytes,1,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Receipt       *Receipt               `protobuf:"bytes,3,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendReceiptRequest) Reset() {
	*x = SendReceiptRequest{}
	mi := &file_terminal_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReceiptRequest) ProtoMessage() {}

func (x *SendReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReceiptRequest.ProtoReflect.Descriptor instead.
func (*SendReceiptRequest) Descriptor() ([]byte, []int) {
	return file_terminal_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *SendReceiptRequest) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *SendReceiptRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *SendReceiptRequest) GetReceipt() *Receipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

type SendReceiptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delivered     bool                   `protobuf:"varint,1,opt,name=delivered,proto3" json:"delivered,omitempty"`
	ErrorReason   string                 `protobuf:"bytes,2,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendReceiptResponse) Reset() {
	*x = SendReceiptResponse{}
	mi := &file_terminal_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendReceiptResponse) ProtoMessage() {}

func (x *SendReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendReceiptResponse.ProtoReflect.Descriptor instead.
func (*SendReceiptResponse) Descriptor() ([]byte, []int) {
	return file_terminal_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *SendReceiptResponse) GetDelivered() bool {
	if x != nil {
		return x.Delivered
	}
	return false
}

func (x *SendReceiptResponse) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

type Receipt struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionId   string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	MerchantName    string                 `protobuf:"bytes,2,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"`
	MerchantAddress string                 `protobuf:"bytes,3,opt,name=merchant_address,json=merchantAddress,proto3" json:"merchant_address,omitempty"`
	TerminalCode    string                 `protobuf:"bytes,4,opt,name=terminal_code,json=terminalCode,proto3" json:"terminal_code,omitempty"`
	Result          ReceiptResult          `protobuf:"varint,5,opt,name=result,proto3,enum=posnet.terminalgateway.v1.ReceiptResult" json:"result,omitempty"`
	AuthCode        string                 `protobuf:"bytes,6,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"`
	RejectionCode   string                 `protobuf:"bytes,7,opt,name=rejection_code,json=rejectionCode,proto3" json:"rejection_code,omitempty"`
	RejectionReason string                 `protobuf:"bytes,8,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	AmountCents     int64                  `protobuf:"varint,9,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	Currency        string                 `protobuf:"bytes,10,opt,name=currency,proto3" json:"currency,omitempty"`
	CardLast4       string                 `protobuf:"bytes,11,opt,name=card_last4,json=cardLast4,proto3" json:"card_last4,omitempty"`
	CardNetwork     string                 `protobuf:"bytes,12,opt,name=card_network,json=cardNetwork,proto3" json:"card_network,omitempty"`
	EntryMode       string                 `protobuf:"bytes,13,opt,name=entry_mode,json=entryMode,proto3" json:"entry_mode,omitempty"`
	TransactionAt   string                 `protobuf:"bytes,14,opt,name=transaction_at,json=transactionAt,proto3" json:"transaction_at,omitempty"` // RFC3339 — sin timestamp.proto
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Receipt) Reset() {
	*x = Receipt{}
	mi := &file_terminal_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Receipt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Receipt) ProtoMessage() {}

func (x *Receipt) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Receipt.ProtoReflect.Descriptor instead.
func (*Receipt) Descriptor() ([]byte, []int) {
	return file_terminal_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *Receipt) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Receipt) GetMerchantName() string {
	if x != nil {
		return x.MerchantName
	}
	return ""
}

func (x *Receipt) GetMerchantAddress() string {
	if x != nil {
		return x.MerchantAddress
	}
	return ""
}

func (x *Receipt) GetTerminalCode() string {
	if x != nil {
		return x.TerminalCode
	}
	return ""
}

func (x *Receipt) GetResult() ReceiptResult {
	if x != nil {
		return x.Result
	}
	return ReceiptResult_RECEIPT_RESULT_UNSPECIFIED
}

func (x *Receipt) GetAuthCode() string {
	if x != nil {
		return x.AuthCode
	}
	return ""
}

func (x *Receipt) GetRejectionCode() string {
	if x != nil {
		return x.RejectionCode
	}
	return ""
}

func (x *Receipt) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

func (x *Receipt) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *Receipt) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Receipt) GetCardLast4() string {
	if x != nil {
		return x.CardLast4
	}
	return ""
}

func (x *Receipt) GetCardNetwork() string {
	if x != nil {
		return x.CardNetwork
	}
	return ""
}

func (x *Receipt) GetEntryMode() string {
	if x != nil {
		return x.EntryMode
	}
	return ""
}

func (x *Receipt) GetTransactionAt() string {
	if x != nil {
		return x.TransactionAt
	}
	return ""
}

type GetTerminalStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TerminalId    string                 `protobuf:"bytes,1,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTerminalStatusRequest) Reset() {
	*x = GetTerminalStatusRequest{}
	mi := &file_terminal_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTerminalStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTerminalStatusRequest) ProtoMessage() {}

func (x *GetTerminalStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTerminalStatusRequest.ProtoReflect.Descriptor instead.
func (*GetTerminalStatusRequest) Descriptor() ([]byte, []int) {
	return file_terminal_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *GetTerminalStatusRequest) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

type GetTerminalStatusResponse struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	TerminalId     string                   `protobuf:"bytes,1,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	Status         TerminalConnectionStatus `protobuf:"varint,2,opt,name=status,proto3,enum=posnet.terminalgateway.v1.TerminalConnectionStatus" json:"status,omitempty"`
	MerchantId     string                   `protobuf:"bytes,3,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	ConnectedSince string                   `protobuf:"bytes,4,opt,name=connected_since,json=connectedSince,proto3" json:"connected_since,omitempty"` // RFC3339
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTerminalStatusResponse) Reset() {
	*x = GetTerminalStatusResponse{}
	mi := &file_terminal_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTerminalStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTerminalStatusResponse) ProtoMessage() {}

func (x *GetTerminalStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_terminal_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTerminalStatusResponse.ProtoReflect.Descriptor instead.
func (*GetTerminalStatusResponse) Descriptor() ([]byte, []int) {
	return file_terminal_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *GetTerminalStatusResponse) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *GetTerminalStatusResponse) GetStatus() TerminalConnectionStatus {
	if x != nil {
		return x.Status
	}
	return TerminalConnectionStatus_TERMINAL_CONNECTION_STATUS_UNSPECIFIED
}

func (x *GetTerminalStatusResponse) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

func (x *GetTerminalStatusResponse) GetConnectedSince() string {
	if x != nil {
		return x.ConnectedSince
	}
	return ""
}

var File_terminal_gateway_proto protoreflect.FileDescriptor

const file_terminal_gateway_proto_rawDesc = "" +
	"\n" +
	"\x16terminal_gateway.proto\x12\x19posnet.terminalgateway.v1\"\x9a\x01\n" +
	"\x12SendReceiptRequest\x12\x1f\n" +
	"\vterminal_id\x18\x01 \x01(\tR\n" +
	"terminalId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12<\n" +
	"\areceipt\x18\x03 \x01(\v2\".posnet.terminalgateway.v1.ReceiptR\areceipt\"V\n" +
	"\x13SendReceiptResponse\x12\x1c\n" +
	"\tdelivered\x18\x01 \x01(\bR\tdelivered\x12!\n" +
	"\ferror_reason\x18\x02 \x01(\tR\verrorReason\"\x9d\x04\n" +
	"\aReceipt\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12#\n" +
	"\rmerchant_name\x18\x02 \x01(\tR\fmerchantName\x12)\n" +
	"\x10merchant_address\x18\x03 \x01(\tR\x0fmerchantAddress\x12#\n" +
	"\rterminal_code\x18\x04 \x01(\tR\fterminalCode\x12@\n" +
	"\x06result\x18\x05 \x01(\x0e2(.posnet.terminalgateway.v1.ReceiptResultR\x06result\x12\x1b\n" +
	"\tauth_code\x18\x06 \x01(\tR\bauthCode\x12%\n" +
	"\x0erejection_code\x18\a \x01(\tR\rrejectionCode\x12)\n" +
	"\x10rejection_reason\x18\b \x01(\tR\x0frejectionReason\x12!\n" +
	"\famount_cents\x18\t \x01(\x03R\vamountCents\x12\x1a\n" +
	"\bcurrency\x18\n" +
	" \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"card_last4\x18\v \x01(\tR\tcardLast4\x12!\n" +
	"\fcard_network\x18\f \x01(\tR\vcardNetwork\x12\x1d\n" +
	"\n" +
	"entry_mode\x18\r \x01(\tR\tentryMode\x12%\n" +
	"\x0etransaction_at\x18\x0e \x01(\tR\rtransactionAt\";\n" +
	"\x18GetTerminalStatusRequest\x12\x1f\n" +
	"\vterminal_id\x18\x01 \x01(\tR\n" +
	"terminalId\"\xd3\x01\n" +
	"\x19GetTerminalStatusResponse\x12\x1f\n" +
	"\vterminal_id\x18\x01 \x01(\tR\n" +
	"terminalId\x12K\n" +
	"\x06status\x18\x02 \x01(\x0e23.posnet.terminalgateway.v1.TerminalConnectionStatusR\x06status\x12\x1f\n" +
	"\vmerchant_id\x18\x03 \x01(\tR\n" +
	"merchantId\x12'\n" +
	"\x0fconnected_since\x18\x04 \x01(\tR\x0econnectedSince*\x86\x01\n" +
	"\rReceiptResult\x12\x1e\n" +
	"\x1aRECEIPT_RESULT_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17RECEIPT_RESULT_APPROVED\x10\x01\x12\x1b\n" +
	"\x17RECEIPT_RESULT_REJECTED\x10\x02\x12\x1b\n" +
	"\x17RECEIPT_RESULT_REVERSED\x10\x03*\xc5\x01\n" +
	"\x18TerminalConnectionStatus\x12*\n" +
	"&TERMINAL_CONNECTION_STATUS_UNSPECIFIED\x10\x00\x12(\n" +
	"$TERMINAL_CONNECTION_STATUS_CONNECTED\x10\x01\x12+\n" +
	"'TERMINAL_CONNECTION_STATUS_DISCONNECTED\x10\x02\x12&\n" +
	"\"TERMINAL_CONNECTION_STATUS_UNKNOWN\x10\x032\x86\x02\n" +
	"\x16TerminalGatewayService\x12l\n" +
	"\vSendReceipt\x12-.posnet.terminalgateway.v1.SendReceiptRequest\x1a..posnet.terminalgateway.v1.SendReceiptResponse\x12~\n" +
	"\x11GetTerminalStatus\x123.posnet.terminalgateway.v1.GetTerminalStatusRequest\x1a4.posnet.terminalgateway.v1.GetTerminalStatusResponseBOZMgithub.com/juantevez/go-posnet/pkg/proto/terminalgateway/v1;terminalgatewayv1b\x06proto3"

var (
	file_terminal_gateway_proto_rawDescOnce sync.Once
	file_terminal_gateway_proto_rawDescData []byte
)

func file_terminal_gateway_proto_rawDescGZIP() []byte {
	file_terminal_gateway_proto_rawDescOnce.Do(func() {
		file_terminal_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_terminal_gateway_proto_rawDesc), len(file_terminal_gateway_proto_rawDesc)))
	})
	return file_terminal_gateway_proto_rawDescData
}

var file_terminal_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_terminal_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_terminal_gateway_proto_goTypes = []any{
	(ReceiptResult)(0),                // 0: posnet.terminalgateway.v1.ReceiptResult
	(TerminalConnectionStatus)(0),     // 1: posnet.terminalgateway.v1.TerminalConnectionStatus
	(*SendReceiptRequest)(nil),        // 2: posnet.terminalgateway.v1.SendReceiptRequest
	(*SendReceiptResponse)(nil),       // 3: posnet.terminalgateway.v1.SendReceiptResponse
	(*Receipt)(nil),                   // 4: posnet.terminalgateway.v1.Receipt
	(*GetTerminalStatusRequest)(nil),  // 5: posnet.terminalgateway.v1.GetTerminalStatusRequest
	(*GetTerminalStatusResponse)(nil), // 6: posnet.terminalgateway.v1.GetTerminalStatusResponse
}
var file_terminal_gateway_proto_depIdxs = []int32{
	4, // 0: posnet.terminalgateway.v1.SendReceiptRequest.receipt:type_name -> posnet.terminalgateway.v1.Receipt
	0, // 1: posnet.terminalgateway.v1.Receipt.result:type_name -> posnet.terminalgateway.v1.ReceiptResult
	1, // 2: posnet.terminalgateway.v1.GetTerminalStatusResponse.status:type_name -> posnet.terminalgateway.v1.TerminalConnectionStatus
	2, // 3: posnet.terminalgateway.v1.TerminalGatewayService.SendReceipt:input_type -> posnet.terminalgateway.v1.SendReceiptRequest
	5, // 4: posnet.terminalgateway.v1.TerminalGatewayService.GetTerminalStatus:input_type -> posnet.terminalgateway.v1.GetTerminalStatusRequest
	3, // 5: posnet.terminalgateway.v1.TerminalGatewayService.SendReceipt:output_type -> posnet.terminalgateway.v1.SendReceiptResponse
	6, // 6: posnet.terminalgateway.v1.TerminalGatewayService.GetTerminalStatus:output_type -> posnet.terminalgateway.v1.GetTerminalStatusResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_terminal_gateway_proto_init() }
func file_terminal_gateway_proto_init() {
	if File_terminal_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_terminal_gateway_proto_rawDesc), len(file_terminal_gateway_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_terminal_gateway_proto_goTypes,
		DependencyIndexes: file_terminal_gateway_proto_depIdxs,
		EnumInfos:         file_terminal_gateway_proto_enumTypes,
		MessageInfos:      file_terminal_gateway_proto_msgTypes,
	}.Build()
	File_terminal_gateway_proto = out.File
	file_terminal_gateway_proto_goTypes = nil
	file_terminal_gateway_proto_depIdxs = nil
}
